#!/bin/sh
output="${1:-xmonad-x86_64-linux}"
mkdir -p "$(dirname "$output")"
exec /usr/bin/ghc --make xmonad.hs -i -ilib -fforce-recomp -main-is main -dynamic -v0 -outputdir "$(dirname "$output")/build-x86_64-linux" -o "$output"
